### ISSUE TITLE
Add `no-hydro-cost` override

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#129]
Hydro cost vary a lot between projects, in particular if the plants contain dams. In that respect, previous studies based on euro-calliope often did not include costs of hydro other than variable cost. Especially when capacity is fixed at today's levels, this is a reasonable modelling decision.

There should be a override that allows to take this decision. [In previous studies](https://github.com/timtroendle/money-land/blob/13c7caa6da34262461d158fcd85b82c069c772c7/src/template/model.yaml#L31), it looked like the following:

```yaml
overrides:
    no-hydro-costs:
        # Because we force all hydro to current levels, there
        # should be annual O&M costs and variable costs only.
        techs.pumped_hydro.costs.monetary.storage_cap: 0
        techs.pumped_hydro.costs.monetary.energy_cap: 0
        techs.hydro_run_of_river.costs.monetary.energy_cap: 0
        techs.hydro_run_of_river.costs.monetary.om_con: 0
        techs.hydro_reservoir.costs.monetary.storage_cap: 0
        techs.hydro_reservoir.costs.monetary.energy_cap: 0
        techs.hydro_reservoir.costs.monetary.om_con: 0
```
