### ISSUE TITLE
Add `stylised-storage` override

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#130]
Previous studies constrained the energy to power ratios of battery and hydrogen. This constraint should be added as an optional override.

In [previous studies](https://github.com/timtroendle/money-land/blob/13c7caa6da34262461d158fcd85b82c069c772c7/src/template/model.yaml#L41), it looked like the following:

```yaml
overrides:
    stylised-storage:
        # Transform battery and hydrogen to stylised short term
        # and long term storage solutions.
        techs:
            battery:
                constraints:
                    energy_cap_per_storage_cap_min: 0.25 # max 4h full-power discharge
                costs:
                    monetary:
                        om_prod: 0 # ASSUME 0 instead of 0.000378 €/kWh, as the tiny number causes numerical issues
            hydrogen:
                constraints:
                    energy_cap_per_storage_cap_max: 0.25 # min 4h full-power discharge
```
