### ISSUE TITLE
Add Danish Energy Agency technology cost data

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/euro-calliope#18]
The Danish Energy Agency provides a comprehensive and regularly updated catalog of technology parameter including cost data.

Euro-calliope should optionally use this data.

https://ens.dk/en/our-services/projections-and-models/technology-data/technology-data-generation-electricity-and

**Comment by fneum** [comment]
Might be an option for you to use https://github.com/PyPSA/technology-data

**Comment by timtroendle** [comment]
It looks great, thanks for the hint @fneum !

**Comment by brynpickering** [comment]
Another source is the UK govt. data on costs: https://www.gov.uk/government/publications/beis-electricity-generation-costs-2020

**Comment by timtroendle** [comment]
@calliope-project/contributors for the help. @FebinKa and I are discussing the definition of done here. What is the most flexible Calliope way of offering the user the choice between JRC and DEA data (and possibly more in the future)?

Should we remove costs from the default files and provide cost overrides with JRC and DEA data, so that the user MUST choose one of them for the model to run?

**Comment by brynpickering** [comment]
Particularly once sector-coupled, there will be more costs that don't overlap between the sources than do (e.g., heating, P2X, & building-level technologies), so it's difficult to imagine being able to have a distinct override file for each source that can be applied in Calliope. One option could be to pre-define some technology-level parameters in the euro-callope config, including where the costs come from. Then, when building the Calliope files, the data is taken from a consolidated CSV based on those parameters. It might make the euro-calliope snakemake config quite long, but at least it would be very explicit. E.g.:

```
parameters:
    tech-data-sources:
       rooftop-pv:
            costs: dea
        wind:
            costs: jrc
```

In the long term, we do intend on having CSV inputs in Calliope. In that case, euro-calliope could output a number of scenario-based CSVs based on my abovementioned parameters, which are then plugged into Calliope by the user.

**Comment by timtroendle** [comment]
The main disadvantage of this approach is that we are completely ignoring the flexibility of Calliope. For pre-builts, but also for projects using euro-calliope as module, models can have exactly one set of cost parameters only.

What about extending your approach by one more level: that level defines an override, and you can have many such overrides. By default, we could have a set of sensible sets of such overrides:


```yaml
model-parameters:
     etri-cost-of-solar-and-wind:
          rooftop-pv:
               costs: jrc
          wind:
               costs: jrc
     schmidt-storage-cost:
          battery:
               cost: schmidt
          ....
```

Also, I'd say let's don't make it more complicated than we need right now, and let's get rid of the superfluous cost level. Then we'd end up with:

```yaml
cost-parameters:
     etri-solar-and-wind:
          rooftop-pv: jrc
          wind: jrc
     schmidt-storage:
          battery: schmidt
          hydrogen: schmidt
          ....
```

What do people think?

**Comment by FebinKa** [comment]
I'm not sure if I understand. The goal would to still have one main set of cost parameters as they are defined right now in `renewable-techs` or `storage-techs` but with pre-defined grouped overrides (e.g in `model.yaml`) that allow the modeller to choose to change the source of the cost data? 

If that's correct, I think this could be a good approach to not overcomplicate things but the definition of done would still not be any clearer to me. Would that be a yaml file in config with the cost data from the different sources so that the overrides can be constructed from it? If I remember correctly, similar pre-defined overrides were already implemented in euro-calliope at one point but I can't seem to find them anymore so I'm not sure how that was done. 
Also, that would not answer the question of which cost data should be used as the default or would you want to not set a default and force the modeller to choose?

**Comment by timtroendle** [comment]
So the suggestion here is that there is a config looking something like this:

```yaml
cost-parameters:
     etri-solar-and-wind-cost:
          rooftop-pv: jrc
          wind: jrc
     schmidt-storage-cost:
          battery: schmidt
          hydrogen: schmidt
          ....
```

Which will create a file `costs.yaml` or so, looking something like this:

```yaml
overrides:
     etri-solar-and-wind-cost:
          techs. rooftop-pv.costs.monetary:
               energy_cap: 88.0 # (10,000 EUR2013/MW) from [@JRC:2014] Table 9
               om_annual: 1.6382360000000002 # (10,000 EUR2013/MW) 2% from [@JRC:2014] Table 9
               om_prod: 0.0001 # (10,000 EUR2013/MW) stolen from om_annual for technical reasons
          techs.wind.costs.monetary:
               [...]
     schmidt-storage-cost:
          techs.battery.costs.monetary:
               storage_cap: 10.123820000000002 # (10,000 EUR2015/MWh), 802 $2015
               energy_cap: 8.558536000000002 # (10,000 EUR2015/MW), 678 $2015
               om_annual: 0.126224 # (10,000 EUR2015/MW/year), 10 $2015
               om_prod: 3.780000000000001e-05 # (10,000 EUR2015/MWh), 3 $2015
          techs.hydrogen.costs.monetary:
               [...]    
```

The file `renewable/storage/transmissions-techs.yaml` would not contain any cost parameters anymore. Therefore, to achieve the current behaviour, the user would need to activate overrides `jrc-solar-and-wind-cost` and `schmidt-storage-cost` (and more). euro-calliope models would not run when not a sufficient amount of overrides are activated covering all technologies.

**Comment by timtroendle** [comment]
Here's a much simpler approach that avoids adding cost to the config (following the discussion during the sprint). We can simply come up with useful default overrides, define them once, and then let the user decide which ones to use.

So there would be a file like this, e.g. `templates/cost-overrides.yaml`:

```yaml
overrides:
     etri-solar-and-wind-cost:
          techs. rooftop-pv.costs.monetary:
               energy_cap: 88.0 # (10,000 EUR2013/MW) from [@JRC:2014] Table 9
               om_annual: 1.6382360000000002 # (10,000 EUR2013/MW) 2% from [@JRC:2014] Table 9
               om_prod: 0.0001 # (10,000 EUR2013/MW) stolen from om_annual for technical reasons
          techs.wind.costs.monetary:
               [...]
     schmidt-storage-cost:
          techs.battery.costs.monetary:
               storage_cap: 10.123820000000002 # (10,000 EUR2015/MWh), 802 $2015
               energy_cap: 8.558536000000002 # (10,000 EUR2015/MW), 678 $2015
               om_annual: 0.126224 # (10,000 EUR2015/MW/year), 10 $2015
               om_prod: 3.780000000000001e-05 # (10,000 EUR2015/MWh), 3 $2015
          techs.hydrogen.costs.monetary:
               [...]  
```
